"""CLI training entry point: builds the model, trains with GPU augmentation, and logs to MLflow."""

from __future__ import annotations

import argparse
import time
from pathlib import Path

import mlflow
import tensorflow as tf
from mlflow.models import infer_signature
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau
from tensorflow.keras.optimizers import Adam

from fashion_mnist.data import configure_gpu, load_fashion_mnist_data
from fashion_mnist.evaluate import evaluate_model
from fashion_mnist.mlflow_utils import MlflowEpochLogger, sanitize_run_name, setup_experiment
from fashion_mnist.model import build_training_model, core_fashion_model


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Train a Fashion MNIST CNN.")

    # Training
    parser.add_argument("--epochs", type=int, default=100)
    parser.add_argument("--batch-size", type=int, default=512)
    parser.add_argument("--learning-rate", type=float, default=0.001)
    parser.add_argument("--val-split", type=float, default=0.1)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--early-stopping-patience", type=int, default=5)
    parser.add_argument("--lr-patience", type=int, default=3)
    parser.add_argument("--lr-factor", type=float, default=0.1)

    # Architecture
    parser.add_argument("--n-conv", type=int, default=4)
    parser.add_argument("--n-dense", type=int, default=2)
    parser.add_argument("--kernel-size", type=int, default=3)
    parser.add_argument(
        "--global-pooling-type", choices=["max", "avg", "flatten"], default="flatten"
    )
    parser.add_argument("--conv-dropout-rate", type=float, default=0.5)
    parser.add_argument("--dense-dropout-rate", type=float, default=0.2)

    # Augmentation
    parser.add_argument("--horizontal-flip", action="store_true")
    parser.add_argument("--rotation", type=float, default=0.0)
    parser.add_argument("--brightness", type=float, default=0.0)
    parser.add_argument("--zoom", type=float, default=0.0)
    parser.add_argument("--translation", type=float, default=0.0)

    # Output
    parser.add_argument("--results-dir", type=Path, default=Path("results"))
    parser.add_argument(
        "--run-name",
        type=str,
        default=None,
        help="Human-readable MLflow run name (e.g. 'baseline'). Auto-generated by "
        "MLflow if omitted.",
    )

    return parser.parse_args()


def main() -> None:
    args = _parse_args()

    configure_gpu()
    tf.keras.utils.set_random_seed(args.seed)

    (train_images, train_labels), (val_images, val_labels), (test_images, test_labels) = (
        load_fashion_mnist_data(val_split=args.val_split)
    )

    core_model = core_fashion_model(
        n_conv=args.n_conv,
        n_dense=args.n_dense,
        kernel_size=args.kernel_size,
        global_pooling_type=args.global_pooling_type,
        conv_dropout_rate=args.conv_dropout_rate,
        dense_dropout_rate=args.dense_dropout_rate,
    )
    # Compiled independently of `training_model` so it can be saved/evaluated on its
    # own later (Keras compile state doesn't transfer between wrapper and submodel).
    core_model.compile(
        optimizer=Adam(learning_rate=args.learning_rate),
        loss="sparse_categorical_crossentropy",
        metrics=["accuracy"],
    )
    training_model = build_training_model(
        core_model,
        horizontal_flip=args.horizontal_flip,
        rotation=args.rotation,
        brightness=args.brightness,
        zoom=args.zoom,
        translation=args.translation,
    )
    training_model.compile(
        optimizer=Adam(learning_rate=args.learning_rate),
        loss="sparse_categorical_crossentropy",
        metrics=["accuracy"],
    )

    setup_experiment()
    with mlflow.start_run(run_name=args.run_name) as run:
        run_id = run.info.run_id
        # Every run gets its own subdirectory locally, named after its MLflow run
        # name (human-readable, auto-generated if not given) plus a short run id
        # suffix for uniqueness, so local artifacts stay recoverable/traceable
        # back to their MLflow run instead of being overwritten by the next call.
        run_dir = args.results_dir / f"{sanitize_run_name(run.info.run_name)}-{run_id[:8]}"
        run_dir.mkdir(parents=True, exist_ok=True)

        mlflow.log_params(
            {
                "learning_rate": args.learning_rate,
                "batch_size": args.batch_size,
                "num_epochs": args.epochs,
                "n_conv": args.n_conv,
                "n_dense": args.n_dense,
                "kernel_size": args.kernel_size,
                "global_pooling_type": args.global_pooling_type,
                "conv_dropout_rate": args.conv_dropout_rate,
                "dense_dropout_rate": args.dense_dropout_rate,
                "horizontal_flip": args.horizontal_flip,
                "rotation": args.rotation,
                "brightness": args.brightness,
                "zoom": args.zoom,
                "translation": args.translation,
                "random_seed": args.seed,
                "optimizer": "adam",
                "loss_function": "sparse_categorical_crossentropy",
            }
        )

        start_time = time.time()
        training_model.fit(
            train_images,
            train_labels,
            batch_size=args.batch_size,
            epochs=args.epochs,
            validation_data=(val_images, val_labels),
            callbacks=[
                EarlyStopping(
                    monitor="val_loss",
                    patience=args.early_stopping_patience,
                    restore_best_weights=True,
                ),
                ReduceLROnPlateau(
                    monitor="val_loss", factor=args.lr_factor, patience=args.lr_patience
                ),
                MlflowEpochLogger(),
            ],
        )
        training_time_seconds = time.time() - start_time

        # `core_model` shares weights with `training_model` (the augmentation head has
        # none), so EarlyStopping's `restore_best_weights` already applies to it here.
        model_path = run_dir / "best_model.keras"
        core_model.save(model_path)

        eval_results = evaluate_model(core_model, test_images, test_labels, run_dir)
        confusion_matrix_path = eval_results.pop("confusion_matrix_path")
        classification_report_path = eval_results.pop("classification_report_path")
        eval_results["training_time_seconds"] = training_time_seconds

        mlflow.log_metrics(eval_results)
        mlflow.log_artifact(str(model_path))
        mlflow.log_artifact(str(confusion_matrix_path))
        mlflow.log_artifact(str(classification_report_path))

        # Signature + input example let MLflow validate inputs and document the
        # expected shape/dtype for downstream inference (`mlflow.pyfunc.load_model`).
        input_example = test_images[:5].numpy()
        signature = infer_signature(input_example, core_model.predict(input_example, verbose=0))
        mlflow.tensorflow.log_model(
            core_model, name="model", signature=signature, input_example=input_example
        )

        print(f"Run: {run.info.run_name} ({run_id})")
        print(f"Saved best model to {model_path}")
        for key, value in eval_results.items():
            print(f"{key}: {value}")


if __name__ == "__main__":
    main()
